name: Build CLI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4

    # Setup Python
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
        cache: 'pip'
        cache-dependency-path: |
          **/requirements*.txt
        
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    # Build python script into a single execute or app folder (macOS)
    - uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: main.py
        mode: app

    # Uploads artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        path: build/imo-utils.bin
        include-hidden-files: true
